# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]
 
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Build with Maven
      run: mvn clean
      
   # - name: Check Vulnerabilities
   #   run: java -javaagent:/home/runner/work/Scan/Scan/contrast.jar -jar /home/runner/work/Scan/Scan/target/SubmissionDataForm-0.0.1-SNAPSHOT.war
   
    - name: Send some mail
      uses: wadeww/send-email-action@master
      with:
        server_address: smtp.gmail.com
       
       # username: bvishali15b@gmail.com
       # password: Vishali@1503
        subject: Workflow finished
        body: Job completed ${{job.status}}
        to: vishaliborra@gmail.com
        from: me
