# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]
 
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Build with Maven
      run: mvn clean install
      
   # - name: Check Vulnerabilities
   #   run: java -javaagent:/home/runner/work/Scan/Scan/contrast.jar -jar /home/runner/work/Scan/Scan/target/SubmissionDataForm-0.0.1-SNAPSHOT.war
   
    - name: Send email
      uses: mmichailidis/sendgrid-mail-action@v1.0
      with:
        sendgrid-token: 'sample'
        mail: 'vishaliborra@gmail.com'
